adding contribution file
Mapepire-IBMi/mapepire-java pull request #7
Opened 2024-08-01 16:29 UTC by AEM100

I have created the contribution file for you, see if you like it or want me to change or add something

![image](https://github.com/user-attachments/assets/81cbc8c6-90b0-42b2-a202-b46ff2fec3f7)

2024-08-14 01:13 UTC, ThePrez commented
@AEM100 thanks for the organized contributions file! Can you please change the build steps from gradlew to mvn?

2024-08-14 02:32 UTC, SanjulaGanepola requested changes
Thanks for adding this file! Just a few minor comments

2024-08-14 02:32 UTC, SanjulaGanepola commented on CONTRIBUTING.md
> +git commit -m "feat: add new feature description"
This should be wrapped in a `sh` code block and should include the `-s` option to sign commits:

```sh
git add .
git commit -s -m "feat: add new feature description"
```

2024-08-14 02:32 UTC, SanjulaGanepola commented on CONTRIBUTING.md
> +We welcome new ideas! If you have a feature request or enhancement suggestion, please open an issue on our [GitHub Issues page](https://github.com/your-username/mapepire-java/issues) and describe the
```suggestion
We welcome new ideas! If you have a feature request or enhancement suggestion, please open an issue on our [GitHub Issues page](https://github.com/Mapepire-IBMi/mapepire-java/issues) and describe the enhancement you'd like to see. 
```

2024-08-19 21:39 UTC, SanjulaGanepola approved these changes
Merging this PR and I will make the relevant fixes in another branch.

2024-08-19 21:39 UTC, merged